#!/bin/bash

CURRENT_SOURCE=$(pactl info | grep "Default Source" | cut -f3 -d" ")

if [ -z $(pactl list sources | grep -A 10 $CURRENT_SOURCE | grep "Mute: no") ]; then
    echo "󰍭"
    echo "󰍭"
    echo "#f38ba8"
fi
