[vscode]
    plugins = [
        ### code
        "bierner.github-markdown-preview",
        "EditorConfig.EditorConfig",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "donjayamanne.githistory",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        "usernamehw.errorlens",
        "wayou.vscode-todo-highlight",
        "humao.rest-client",
        ### look & feel
        "Catppuccin.catppuccin-vsc",
        "Catppuccin.catppuccin-vsc-icons",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
