#############
### setup ###
#############

[packages.macos]
    taps = [
        "homebrew/cask-fonts",
    ]
    formulae = [
        "ack",
        "asdf",
        "bat",
        "btop",
        "curl",
        "exa",
        "exiftool",
        "fd",
        "fzf",
        "git",
        "git-delta",
        "helm",
        "imagemagick",
        "jpeg",
        "k9s",
        "kubernetes-cli",
        "minikube",
        "neofetch",
        "neovim",
        "pandoc",
        "potrace",
        "ripgrep",
        "the_silver_searcher",
        "tldr",
        "tmux",
        "tmuxinator",
        "wget",
        "zsh",
    ]
    casks = [
        "font-caskaydia-cove-nerd-font",
    ]
    casks_gui = [
        "docker",
        "firefox",
        "google-chrome",
        "hyper",
        "keepassxc",
        "visual-studio-code",
    ]

[packages.ubuntu]
    repositories = [
        { name = "docker", key = "https://download.docker.com/linux/ubuntu/gpg", url = "https://download.docker.com/linux/ubuntu", dist = "$(. /etc/os-release && echo \"$VERSION_CODENAME\")", comp = "stable" },
        { name = "google-chrome", key = "https://dl.google.com/linux/linux_signing_key.pub", url = "http://dl.google.com/linux/chrome/deb/", dist = "stable", comp = "main" },
        { name = "helm", key = "https://baltocdn.com/helm/signing.asc", url = "https://baltocdn.com/helm/stable/debian/", dist = "all", comp = "main" },
        { name = "kubernetes", key = "https://packages.cloud.google.com/apt/doc/apt-key.gpg", url = "https://apt.kubernetes.io/", dist = "kubernetes-xenial", comp = "main" },
    ]
    headless = [
        "ack",
        # asdf
        "bat",
        "btop",
        "cmake",
        "curl",
        "containerd.io",  # docker repo
        "docker-buildx-plugin",  # docker repo
        "docker-ce",  # docker repo
        "docker-ce-cli",  # docker repo
        "docker-compose-plugin",  # docker repo
        "exa",
        "fd-find",
        "fzf",
        "gcc",
        "git",
        "gnupg",
        "helm",  # helm repo
        "kubectl",  # kubernetes repo
        "libffi-dev",
        "libimage-exiftool-perl",
        "libsqlite3-dev",
        "libssl-dev",
        "libyaml-dev",
        "make",
        # minikube
        "neofetch",
        #"neovim",
        "pandoc",
        "python3",
        "python3-pip",
        "python3-venv",
        "ripgrep",
        "silversearcher-ag",
        "tldr",
        "tmux",
        "tmuxinator",
        "zlib1g-dev",
        "zsh",
    ]
    gui = [
        "firefox",
        "google-chrome-stable",  # google-chrome repo
        "keepassxc",
    ]
    snaps = [
        "k9s",
        "nvim --classic",
    ]
    snaps_gui = [
        "code --classic",
    ]

[packages.windows]
    headless = [
        "dandavison.delta",
        "twpayne.chezmoi",
    ]
    gui = [
        "9MTFTXSJ9M7F --source msstore  # RoundedTB",
        "9NCBCSZSJRSB --source msstore  # Spotify",
        "9PDXGNCFSCZV --source msstore  # Ubuntu (WSL)",
        "Google.Chrome",
        "KeePassXCTeam.KeePassXC",
        "Logseq.Logseq",
        "Microsoft.VisualStudioCode",
        "Mozilla.Firefox",
        "Nextcloud.NextcloudDesktop",
        "QMK.QMKToolbox",
        "Spotify.Spotify",
        #"Vercel.Hyper",
    ]
    gaming = [
        "Discord.Discord",
        "GOG.Galaxy",
        "Valve.Steam",
    ]

[plugins]
    chrome = [
        "bkkmolkhemgaeaeggcmfbghljjjoofoh",  # Catppuccin Mocha
        "oboonakemofpalcgghocfoadofidjkkk",  # KeePassXC-Browser
        "clngdbkpkpeebahjckkjfobafhncgmne",  # Stylus
    ]
    chrome_urls = [
        "https://github.com/catppuccin/userstyles/raw/main/styles/github/catppuccin.user.css",
        "https://github.com/catppuccin/userstyles/raw/main/styles/mastodon/catppuccin.user.css",
        "https://github.com/catppuccin/userstyles/raw/main/styles/reddit/catppuccin.user.css",
        "https://github.com/catppuccin/userstyles/raw/main/styles/twitch/catppuccin.user.css",
        "https://github.com/catppuccin/userstyles/raw/main/styles/whatsapp-web/catppuccin.user.css",
        "https://github.com/catppuccin/userstyles/raw/main/styles/youtube/catppuccin.user.css",
    ]
    vscode = [
        ### code
        "bierner.github-markdown-preview",
        "EditorConfig.EditorConfig",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "donjayamanne.githistory",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        "usernamehw.errorlens",
        "wayou.vscode-todo-highlight",
        "humao.rest-client",
        ### look & feel
        "Catppuccin.catppuccin-vsc",
        "Catppuccin.catppuccin-vsc-icons",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
