################
### settings ###
################

[system]
    locale = "en-DE"
    region = "de-DE"
    geoid = "0x5e"


##############
### design ###
##############

[colors]
    background           = "#2E3440"  # nord0
    backgroundElement    = "#3B4252"  # nord1
    backgroundHighlight  = "#434C5E"  # nord2
    backgroundText       = "#4C566A"  # nord3

    foregroundElement    = "#D8DEE9"  # nord4
    foregroundMuted      = "#E5E9F0"  # nord5
    foreground           = "#ECEFF4"  # nord6

    primaryHighlight     = "#8FBCBB"  # nord7
    primary              = "#88C0D0"  # nord8
    secondary            = "#81A1C1"  # nord9
    tertiary             = "#5E81AC"  # nord10

    black                = "#3B4252"  # nord1
    grey                 = "#4C566A"  # nord3
    white                = "#ECEFF4"  # nord6
    red                  = "#BF616A"  # nord11
    orange               = "#D08770"  # nord12
    yellow               = "#EBCB8B"  # nord13
    green                = "#A3BE8C"  # nord14
    magenta              = "#B48EAD"  # nord15
    cyan                 = "#88C0D0"  # nord5
    blue                 = "#81A1C1"  # nord9


#############
### setup ###
#############

[packages.macos]
    headless.formulae = [
        "ack",
        "asdf",
        "bat",
        "btop",
        "curl",
        "exa",
        "exiftool",
        "fd",
        "fzf",
        "git",
        "git-delta",
        "helm",
        "imagemagick",
        "jpeg",
        "k9s",
        "kubernetes-cli",
        "minikube",
        "neofetch",
        "neovim",
        "potrace",
        "the_silver_searcher",
        "tldr",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.casks = []
    gui.formulae = []
    gui.casks = [
        "docker",
        "hyper",
        "keepassxc",
        "visual-studio-code",
    ]

[packages.ubuntu]
    repositories = [
        { name = "docker", key = "https://download.docker.com/linux/ubuntu/gpg", url = "https://download.docker.com/linux/ubuntu", dist = "$(. /etc/os-release && echo \"$VERSION_CODENAME\")", comp = "stable" },
        { name = "helm", key = "https://baltocdn.com/helm/signing.asc", url = "https://baltocdn.com/helm/stable/debian/", dist = "all", comp = "main" },
        { name = "kubernetes", key = "https://packages.cloud.google.com/apt/doc/apt-key.gpg", url = "https://apt.kubernetes.io/", dist = "kubernetes-xenial", comp = "main" },
    ]
    headless.apt = [
        "ack",
        # asdf
        "bat",
        "btop",
        "curl",
        "containerd.io",  # docker repo
        "docker-buildx-plugin",  # docker repo
        "docker-ce",  # docker repo
        "docker-ce-cli",  # docker repo
        "docker-compose-plugin",  # docker repo
        "exa",
        "fd-find",
        "fzf",
        "git",
        "gnupg",
        "helm",  # helm repo
        "kubectl",  # kubernetes repo
        "libimage-exiftool-perl",
        # minikube
        "neofetch",
        "neovim",
        "silversearcher-ag",
        "tldr",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.snaps = [
        "k9s",
    ]
    gui.apt = [
        "keepassxc",
    ]
    gui.snaps = [
        "code --classic",
    ]

[packages.windows]
    headless.winget = [
        "dandavison.delta",
        "twpayne.chezmoi",
    ]
    gui.winget = [
        "9MTFTXSJ9M7F --source msstore  # RoundedTB",
        "9NCBCSZSJRSB --source msstore  # Spotify",
        "9PDXGNCFSCZV --source msstore  # Ubuntu (WSL)",
        "Google.Chrome",
        "KeePassXCTeam.KeePassXC",
        "Logseq.Logseq",
        "Microsoft.VisualStudioCode",
        "Neovim.Neovim",
        "Nextcloud.NextcloudDesktop",
        "Spotify.Spotify",
        #"Vercel.Hyper",
    ]
    gaming.winget = [
        "Discord.Discord",
        "GOG.Galaxy",
        "Valve.Steam",
    ]

[plugins]
    vscode = [
        ### code
        "bierner.github-markdown-preview",
        "EditorConfig.EditorConfig",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "donjayamanne.githistory",
        "esbenp.prettier-vscode",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        "usernamehw.errorlens",
        "wayou.vscode-todo-highlight",
        "humao.rest-client",
        ### look & feel
        "arcticicestudio.nord-visual-studio-code",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
