[packages.macos]
    headless.formulae = [
        "curl",
        "git",
        "neofetch",
        "neovim",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.casks = []
    gui.formulae = []
    gui.casks = [
        "google-chrome",
        "visual-studio-code",
    ]

[packages.ubuntu]
    gui.apt = []
    headless.apt = [
        "curl",
        "git",
        "neofetch",
        "neovim",
        "tmux",
        "tmuxinator",
        "zsh",
    ]

[packages.windows]
    headless.chocolatey = []
    gui.chocolatey = [
        "hyper",
        "vscode",
    ]

[plugins]
    vscode = [
        ### code
        "bierner.github-markdown-preview",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "esbenp.prettier-vscode",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        ### look & feel
        "arcticicestudio.nord-visual-studio-code",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
