[packages.macos]
    headless.formulae = [
        "curl",
        "fd",
        "git",
        "helm",
        "k9s",
        "kubernetes-cli",
        "minikube",
        "neofetch",
        "neovim",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.casks = []
    gui.formulae = []
    gui.casks = [
        "docker",
        "hyper",
        "keepassxc",
        "visual-studio-code",
    ]

[packages.ubuntu]
    headless.apt = [
        "curl",
        # docker
        "fd-find",
        "git",
        "gnupg",
        "neofetch",
        "neovim",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.snaps = [
        "--classic helm",
        "k9s",
        "--classic kubectl",
        "minikube",
    ]
    gui.apt = [
        "keepassxc",
    ]
    gui.snaps = [
        "--classic code",
    ]

[packages.windows]
    headless.chocolatey = []
    gui.chocolatey = [
        "hyper",
        "keepassxc",
        "vscode",
    ]

[plugins]
    vscode = [
        ### code
        "bierner.github-markdown-preview",
        "EditorConfig.EditorConfig",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "donjayamanne.githistory",
        "esbenp.prettier-vscode",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        "usernamehw.errorlens",
        "wayou.vscode-todo-highlight",
        "humao.rest-client",
        ### look & feel
        "arcticicestudio.nord-visual-studio-code",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
