[packages.macos]
    headless.formulae = [
        "zsh",
        "neovim",
        "tmux",
        "tmuxinator",
        "neofetch",
        "git",
        "curl",
    ]
    headless.casks = []
    gui.formulae = []
    gui.casks = [
        "google-chrome",
        "visual-studio-code",
    ]

[packages.ubuntu]
    gui.apt = []
    headless.apt = [
        "zsh",
        "neovim",
        "tmux",
        "tmuxinator",
        "neofetch",
        "git",
        "curl",
    ]

[packages.windows]
    headless.chocolatey = []
    gui.chocolatey = [
        "hyper",
        "vscode",
    ]

[plugins]
    vscode = [
        # code
        "bierner.github-markdown-preview",
        # tools
        "eamodio.gitlens",
        "GitHub.copilot",
        "pnp.polacode",
        "esbenp.prettier-vscode",
        # look & feel
        "arcticicestudio.nord-visual-studio-code",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
