################
### settings ###
################

[system]
    locale = "en-DE"
    region = "de-DE"
    geoid = "0x5e"


#############
### setup ###
#############

[packages.macos]
    headless.taps = [
        "homebrew/cask-fonts",
    ]
    headless.formulae = [
        "ack",
        "asdf",
        "bat",
        "btop",
        "curl",
        "exa",
        "exiftool",
        "fd",
        "fzf",
        "git",
        "git-delta",
        "helm",
        "imagemagick",
        "jpeg",
        "k9s",
        "kubernetes-cli",
        "minikube",
        "neofetch",
        "neovim",
        "potrace",
        "the_silver_searcher",
        "tldr",
        "tmux",
        "tmuxinator",
        "wget",
        "zsh",
    ]
    headless.casks = [
        "font-caskaydia-cove-nerd-font",
    ]
    gui.formulae = []
    gui.casks = [
        "docker",
        "hyper",
        "keepassxc",
        "visual-studio-code",
    ]

[packages.ubuntu]
    repositories = [
        { name = "docker", key = "https://download.docker.com/linux/ubuntu/gpg", url = "https://download.docker.com/linux/ubuntu", dist = "$(. /etc/os-release && echo \"$VERSION_CODENAME\")", comp = "stable" },
        { name = "helm", key = "https://baltocdn.com/helm/signing.asc", url = "https://baltocdn.com/helm/stable/debian/", dist = "all", comp = "main" },
        { name = "kubernetes", key = "https://packages.cloud.google.com/apt/doc/apt-key.gpg", url = "https://apt.kubernetes.io/", dist = "kubernetes-xenial", comp = "main" },
    ]
    headless.apt = [
        "ack",
        # asdf
        "bat",
        "btop",
        "curl",
        "containerd.io",  # docker repo
        "docker-buildx-plugin",  # docker repo
        "docker-ce",  # docker repo
        "docker-ce-cli",  # docker repo
        "docker-compose-plugin",  # docker repo
        "exa",
        "fd-find",
        "fzf",
        "gcc",
        "git",
        "gnupg",
        "helm",  # helm repo
        "kubectl",  # kubernetes repo
        "libimage-exiftool-perl",
        "make",
        # minikube
        "neofetch",
        #"neovim",
        "silversearcher-ag",
        "tldr",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.snaps = [
        "k9s",
        "nvim --classic",
    ]
    gui.apt = [
        "keepassxc",
    ]
    gui.snaps = [
        "code --classic",
    ]

[packages.windows]
    headless.winget = [
        "dandavison.delta",
        "twpayne.chezmoi",
    ]
    gui.winget = [
        "9MTFTXSJ9M7F --source msstore  # RoundedTB",
        "9NCBCSZSJRSB --source msstore  # Spotify",
        "9PDXGNCFSCZV --source msstore  # Ubuntu (WSL)",
        "Google.Chrome",
        "KeePassXCTeam.KeePassXC",
        "Logseq.Logseq",
        "Microsoft.VisualStudioCode",
        "Nextcloud.NextcloudDesktop",
        "Spotify.Spotify",
        #"Vercel.Hyper",
    ]
    gaming.winget = [
        "Discord.Discord",
        "GOG.Galaxy",
        "Valve.Steam",
    ]

[plugins]
    vscode = [
        ### code
        "bierner.github-markdown-preview",
        "EditorConfig.EditorConfig",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "donjayamanne.githistory",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        "usernamehw.errorlens",
        "wayou.vscode-todo-highlight",
        "humao.rest-client",
        ### look & feel
        "Catppuccin.catppuccin-vsc",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
