[packages.macos]
    headless.formulae = [
        "ack",
        "bat",
        "btop",
        "curl",
        "exiftool",
        "fd",
        "fzf",
        "git",
        "git-delta",
        "helm",
        "k9s",
        "kubernetes-cli",
        "minikube",
        "neofetch",
        "neovim",
        "the_silver_searcher",
        "tldr",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.casks = []
    gui.formulae = []
    gui.casks = [
        "docker",
        "hyper",
        "keepassxc",
        "visual-studio-code",
    ]

[packages.ubuntu]
    repositories = [
        { name = "docker", key = "https://download.docker.com/linux/ubuntu/gpg", url = "https://download.docker.com/linux/ubuntu", dist = "$(. /etc/os-release && echo \"$VERSION_CODENAME\")", comp = "stable" },
        { name = "kubernetes", key = "https://packages.cloud.google.com/apt/doc/apt-key.gpg", url = "https://apt.kubernetes.io/", dist = "kubernetes-xenial", comp = "main" },
        { name = "helm", key = "https://baltocdn.com/helm/signing.asc", url = "https://baltocdn.com/helm/stable/debian/", dist = "all", comp = "main" },
    ]
    headless.apt = [
        "ack",
        "bat",
        "btop",
        "curl",
        "containerd.io",          # docker repo
        "docker-buildx-plugin",   # docker repo
        "docker-ce",              # docker repo
        "docker-ce-cli",          # docker repo
        "docker-compose-plugin",  # docker repo
        "fd-find",
        "fzf",
        "git",
        "gnupg",
        "helm",                   # helm repo
        "kubectl",                # kubernetes repo
        "libimage-exiftool-perl",
        # minikube in .chezmoiexternal
        "neofetch",
        "neovim",
        "silversearcher-ag",
        "tldr",
        "tmux",
        "tmuxinator",
        "zsh",
    ]
    headless.snaps = [
        "k9s",
    ]
    gui.apt = [
        "keepassxc",
    ]
    gui.snaps = [
        "--classic code",
    ]

[packages.windows]
    headless.chocolatey = []
    gui.chocolatey = [
        "hyper",
        "keepassxc",
        "vscode",
    ]

[plugins]
    vscode = [
        ### code
        "bierner.github-markdown-preview",
        "EditorConfig.EditorConfig",
        ### environment
        "GitHub.codespaces",
        "ms-azuretools.vscode-docker",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "ms-vscode-remote.vscode-remote-extensionpack",
        ### tools
        "eamodio.gitlens",
        "donjayamanne.githistory",
        "esbenp.prettier-vscode",
        "GitHub.copilot",
        "GitHub.vscode-pull-request-github",
        "pnp.polacode",
        "usernamehw.errorlens",
        "wayou.vscode-todo-highlight",
        "humao.rest-client",
        ### look & feel
        "arcticicestudio.nord-visual-studio-code",
        "equinusocio.vsc-material-theme-icons",
        "vscodevim.vim",
    ]
