#!/bin/sh

# run ~/.xprofile
[[ -f ~/.xprofile ]] && . ~/.xprofile

# load ~/.Xresources
# most distplay managers do this automatically
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# start i3wm
#export XDG_CURRENT_DESKTOP=GNOME
exec i3
